# Dockerfile for testing the OMERO Linux installation instructions
# Not intended for production use
FROM ubuntu:14.04
MAINTAINER ome-devel@lists.openmicroscopy.org.uk

RUN update-locale LANG=C.UTF-8

ADD ./omeroweb-install-test.zip /tmp/omeroweb-install/
RUN apt-get update && apt-get -y install unzip
RUN unzip /tmp/omeroweb-install/omeroweb-install-test.zip -d /tmp/omeroweb-install/

RUN update-locale LANG=C.UTF-8

# This is so that scripts can detect whether they're in docker
RUN echo 'export container=docker' > /etc/profile.d/docker.sh

ARG WEBSESSION=false
ARG ICEVER=3.6
ARG OS=ubuntu
ARG OMEROVER=latest
ARG WEBPORT=80

RUN OS=$OS OMEROVER=$OMEROVER WEBPORT=$WEBPORT ICEVER=$ICEVER WEBSESSION=$WEBSESSION \
    /tmp/omeroweb-install/omeroweb-install-test/install.sh

EXPOSE 22 80

ADD ./run.sh /home/omero/run.sh
CMD ["/bin/bash", "-e", "/home/omero/run.sh"]

