# Dockerfile for testing the OMERO Linux installation instructions
# Not intended for production use
# Note to enable systemd this must be run with on a host with systemd
# and additional flaks, see the omero-ssh-c7 README
FROM openmicroscopy/omero-ssh-c7:0.1.0
MAINTAINER ome-devel@lists.openmicroscopy.org.uk

# Remove the existing omero user
RUN userdel -r omero && \
	rm -f /etc/sudoers.d/omero && \
	echo 'root:omero' | chpasswd

ADD ./omeroweb-install-test.zip /tmp/omeroweb-install/
RUN yum -y install initscripts unzip
RUN unzip /tmp/omeroweb-install/omeroweb-install-test.zip -d /tmp/omeroweb-install/

# This is so that scripts can detect whether they're in docker
RUN echo 'export container=docker' > /etc/profile.d/docker.sh

ARG WEBSESSION=false
ARG ICEVER=3.6
ARG OS=centos7
ARG OMERO_USER=omero
ARG OMEROVER=latest
ARG WEBPORT=80

RUN OMERO_USER=$OMERO_USER OS=$OS \
    OMEROVER=$OMEROVER WEBPORT=$WEBPORT \
    ICEVER=$ICEVER WEBSESSION=$WEBSESSION \
    /tmp/omeroweb-install/omeroweb-install-test/install.sh

EXPOSE 22 80
