# Dockerfile for testing the OMERO Rocky Linux installation instructions
# Not intended for production use
# Note to enable systemd this must be run with on a host with systemd
FROM rockylinux:9
LABEL author="ome-devel@lists.openmicroscopy.org.uk"

RUN touch /.dockerenv

ADD ./omeroweb-install-test.zip /tmp
RUN dnf -y install initscripts unzip
RUN unzip /tmp/omeroweb-install-test.zip -d /tmp

# This is so that scripts can detect whether they're in docker
RUN touch /.dockerenv

ARG ICEVER=3.6
ARG WEBPORT=80
ARG WEBPREFIX
ARG WEBSESSION
ARG WEBSERVER_CONF
ARG WEBSERVER_NAME

RUN ICEVER=$ICEVER \
    WEBPORT=$WEBPORT WEBPREFIX=$WEBPREFIX WEBSESSION=$WEBSESSION \
    WEBSERVER_CONF=$WEBSERVER_CONF WEBSERVER_NAME=$WEBSERVER_NAME \
    /tmp/omeroweb-install-test/omeroweb-install-rockylinux9-ice${ICEVER}

EXPOSE 22 80
