#!/bin/bash

set -e -u -x

while [[ $# -gt 0 ]] && [[ ."$1" = .--* ]] ;
do
    opt="$1";
    shift;
    case "$opt" in
        --os=*)
            os="${opt#*=}"
            ;;
        --ice-version=*)
            ice_version="${opt#*=}"
            ;;
        *)
                # unknown option
        ;;
esac
done

path=`dirname $0`

if [ "$ice_version" == "3.5" ]; then
    system_site_packages="True"
fi

# clean
rm -rf $path/${os}-ice${ice_version} $path/doc/omeroweb-install-${os}.txt

# build
mkdir -p $path/${os}-ice${ice_version}
ansible-playbook $path/ansible/omeroweb-install.yml -i $path/ansible/hosts/${os}-ice${ice_version} --extra-vars "os=${os} ice_version=${ice_version} system_site_packages=${system_site_packages:-}" 

# build doc
mkdir -p $path/doc
ansible-playbook $path/ansible/omeroweb-install-doc.yml -i $path/ansible/hosts/${os}-ice${ice_version} --extra-vars "os=${os} ice_version=${ice_version} system_site_packages=${system_site_packages:-}"
